name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read
  deployments: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Zola 0.21.0
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.21.0

      - name: Build site
        run: zola build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CF_PAGES_PROJECT_NAME }}
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'


